# Generated by Django 5.1.3 on 2024-12-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_is_playing_room_video_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_movie_sync_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
